### ISSUE TITLE
Copy of Whiteboard event tracking prototype

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/whiteboard-collaboration-service#38]
## Description

As a sys admin I want to know all changes that take place on a particular whiteboard

## Acceptance criteria

- [ ] Allow whiteboard events to be submitted to Elastic
- [ ] Whiteboard event logging to have three levels: none, light, full. None = no events sent to Elastic, Light: user + event type sent, Full = Light plus delta of what was changed
- [ ]  Elastic / Kibana to have ability to show all events for a particular whiteboard. 

Tbd: any Kibana report that makes sense e.g. # of whiteboards, whiteboard events over time, whiteboard events per space? To be taken separately. 

## Additional Context
Assuming stay with a single whiteboard collaboration instance for now.
